[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci --only=production --no-audit --prefer-offline --no-fund']

[phases.build]
cmds = [
  'cd client && npm ci --only=production --no-audit --prefer-offline --no-fund',
  'cd client && npm run build'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
